### ISSUE TITLE
Chapter 11 Topic 5 | Link to file leads to a repository page

### ISSUE THREAD

**Issue by isse-ahmed** [University-of-Manitoba-Computer-Science/tools-n-techniques#11]
## The Issue
In the, *Run a command within a container*, topic of chapter 11, we are given a link to download a file from, however, the link does not lead to the raw file so we cannot use `wget` to install it. In other parts of the textbook, we are given links that we can use `wget` on.

### Chapter 11 Topic 5 [Current State]
```markdown
We’re going to use [pandocker](https://github.com/dalibo/pandocker). Let’s write ourselves a little Markdown file that takes advantage of some features in [pandocker](https://github.com/dalibo/pandocker) that we can’t do with the base pandoc install:

`https://code.cs.umanitoba.ca/cs-lab-course/hello-pandocker` //Link leads to repository page, cannot `wget`

You should use this file to: //Wording sounds like the link is to a file
```

### Chapter 11 Topic 5 [Changed Link]

```markdown
We’re going to use [pandocker](https://github.com/dalibo/pandocker). Let’s write ourselves a little Markdown file that takes advantage of some features in [pandocker](https://github.com/dalibo/pandocker) that we can’t do with the base pandoc install:

`https://code.cs.umanitoba.ca/cs-lab-course/hello-pandocker/-/raw/main/hello-pandocker.md`  //Works with `wget`

You should use this file to: 
```

### Example from Chapter 10 Topic 3

Here we are given a link that works with `wget`, something I have come to expect unless its explicitly stated to use another method.

```markdown
Re-download or copy hello.tar.gz:

`https://university-of-manitoba-computer-science.github.io/tools-n-techniques/topic07/hello.tar.gz`
```

**Comment by fbristow** [comment]
Thank you for reporting this @isse-ahmed!

The styling is indeed inconsistent with your expectation. I'll update the link to point directly at the file `hello-pandocker.md` as you're suggesting so that readers can `wget` or `curl` the link.
